# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: gwells <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2016/08/24 13:34:18 by gwells            #+#    #+#              #
#    Updated: 2016/09/08 20:18:56 by fviolin          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = 42sh

C_DIR = sources
C_DIRS = $(shell find $(C_DIR) -type d -follow -print)
C_FILES = $(shell find $(C_DIRS) -type f -follow -print | grep -w "[.c]$$")

O_DIR = .tmp/obj
O_DIRS = $(C_DIRS:$(C_DIR)%=$(O_DIR)%)
O_FILES = $(C_FILES:$(C_DIR)%.c=$(O_DIR)%.o)

FLAGS = -Wall -Werror -Wextra
INCLUDES = -Iincludes -Ilibft
LIB = -L./libft -lft -lncurses

all: $(NAME)

$(NAME): $(O_FILES)
		make -C ./libft
		gcc $(FLAGS) $^ $(LIB) -o $@
		touch ./sources/.history

$(O_DIR)%.o: $(C_DIR)%.c
		mkdir -p $(O_DIRS) $(O_DIR)
		gcc $(FLAGS) $(INCLUDES) -o $@ -c $<
		touch .history

clean:	
	rm -rf $(O_FILES)
	make clean -C libft

fclean: clean
	@make fclean -C libft
	@rm $(NAME) || true
	@rm -rf .tmp/

re: fclean all

.PHONY : all clean fclean re
